# DataFrame Merge

서로 다른 두 개의 DataFrame을 하나로 합치는 작업은 두 가지 방식으로 구분할 수 있음.

 * concatenating(연결) : 단순히 하나의 DataFrame에 다른 DataFrame을 연속적으로 붙이는 방식

 * merging(병합) : 두 DataFrame에 공통적으로 포함되어 있는 하나의 열을 기준으로 삼아, 해당 열의 값이 동일한 두 개의 행들을 하나의 행으로 합치는 방식

## 1. Merging DataFrame

**열 기준 Merging**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({'key': list('bbacaab'),
                   'data': range(7)})
df2 = pd.DataFrame({'key': list('abd'),
                   'data2': range(3)})

In [3]:
df1

   data key
0     0   b
1     1   b
2     2   a
3     3   c
4     4   a
5     5   a
6     6   b

In [4]:
df2

   data2 key
0      0   a
1      1   b
2      2   d

In [5]:
# key 열을 기준으로 하여 두 DataFrame에 대한 merging을 수행
# == db의 inner join과 같은 역할
pd.merge(df1, df2, on ='key')

   data key  data2
0     0   b      1
1     1   b      1
2     6   b      1
3     2   a      0
4     4   a      0
5     5   a      0

In [6]:
# how 인자의 값을 outer로 하면 다른 조합 방식에 따라 새로운 행들을 생성함
# == db의 outer join과 같은 역할
pd.merge(df1, df2, on='key', how='outer')

   data key  data2
0   0.0   b    1.0
1   1.0   b    1.0
2   6.0   b    1.0
3   2.0   a    0.0
4   4.0   a    0.0
5   5.0   a    0.0
6   3.0   c    NaN
7   NaN   d    2.0

In [7]:
# left(df1) 기준으로 merge
# == left join 같은 기능
pd.merge(df1, df2, on='key', how ='left')

   data key  data2
0     0   b    1.0
1     1   b    1.0
2     2   a    0.0
3     3   c    NaN
4     4   a    0.0
5     5   a    0.0
6     6   b    1.0

In [8]:
# right(df2) 기준으로 merge
# == right join 같은 기능
pd.merge(df1, df2, on='key', how ='right')

   data key  data2
0   0.0   b      1
1   1.0   b      1
2   6.0   b      1
3   2.0   a      0
4   4.0   a      0
5   5.0   a      0
6   NaN   d      2

In [12]:
# merge하고자 하는 기준 열의 이름이 다른 경우의 merge 방법

df3 = pd.DataFrame({'lkey': list('bbacaab'),
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': list('abd'),
                   'data2': range(3)})

In [13]:
df3

   data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [14]:
df4

   data2 rkey
0      0    a
1      1    b
2      2    d

In [15]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

   data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

**인덱스 기준 merging**

In [16]:
left1 = pd.DataFrame({'key': ['a','b','a','a','b','c'],
                     'value': range(6)})
right1 = pd.DataFrame({'group_val':[3.5, 7]},
                      index=['a','b'])

In [17]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [18]:
right1

   group_val
a        3.5
b        7.0

In [24]:
# left1에서 'key'열을, right1에서는 인덱스를 기준으로 merging을 수행
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [25]:
#두 DataFrame 모두 인덱스 기준으로 merging을 수행하고자 할 경우

left2 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                    index=['a','c','e'], columns=['Seoul','Incheon'])
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                     index=['b','c','d','e'], columns=['Daegu', 'Ulsan'])

In [26]:
left2

   Seoul  Incheon
a    1.0      2.0
c    3.0      4.0
e    5.0      6.0

In [27]:
right2

   Daegu  Ulsan
b    7.0    8.0
c    9.0   10.0
d   11.0   12.0
e   13.0   14.0

In [28]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

   Seoul  Incheon  Daegu  Ulsan
a    1.0      2.0    NaN    NaN
b    NaN      NaN    7.0    8.0
c    3.0      4.0    9.0   10.0
d    NaN      NaN   11.0   12.0
e    5.0      6.0   13.0   14.0

** Concatenating DataFrame**

*: Concatenating은 쉽게 말해서 하나의 DataFrame에 다른 DataFrame을 행 방향 또는 열 방향으로 단순 연결하는 것을 의미*

In [43]:
# Series data concatenating

s1 = pd.Series([0,1], index=['a', 'b'])
s2 = pd.Series([2,3,4], index=['c','d','e'])
s3 = pd.Series([5,6], index=['f','g'])

In [30]:
s1

a    0
b    1
dtype: int64

In [31]:
s2

c    2
d    3
e    4
dtype: int64

In [32]:
s3

f    5
g    6
dtype: int64

In [48]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [33]:
# axis=1 인자를 명시하면 Series가 2차원적으로 연결
pd.concat([s1,s2,s3], axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [40]:
s4 = pd.concat([(s1*5), s3])

In [39]:
pd.concat([s1,s4], axis=1)

     0   1
a  0.0   0
b  1.0   5
f  NaN  10
g  NaN  12

In [42]:
# concatenating 진행시, key값으로 컬럼을 명시할 수 있음
pd.concat([s1,s2,s3], axis=1, keys=['one','two','three'])

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [59]:
# DataFrame Concatenating

df1 = pd.DataFrame(np.arange(6).reshape(3,2),
                  index=['a','b','c'], columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2),
                  index=['a','c'], columns=['three','four'])

In [60]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [61]:
df2

   three  four
a      5     6
c      7     8

In [63]:
pd.concat([df1, df2], axis=1)

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [48]:
# 행방향으로 concatenating을 수행할 때 기존 dataframe의 인덱스가 유지되었는데,
# ignore_index=True 인자를 넣어주면 기존의 인덱스를 무시하고 새로운 인덱스를 붙여줌

df3 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df4 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [49]:
df3

          a         b         c         d
0 -1.049516 -0.782308  0.068325 -0.663225
1 -1.125727  0.624032 -1.113899  0.774512
2  1.920055 -0.749316 -0.492838 -0.894182

In [50]:
df4

          b         d         a
0 -0.048233  1.102955 -0.490303
1  1.471812  0.940594 -0.583081

In [51]:
pd.concat([df3, df4], ignore_index=True)

          a         b         c         d
0 -1.049516 -0.782308  0.068325 -0.663225
1 -1.125727  0.624032 -1.113899  0.774512
2  1.920055 -0.749316 -0.492838 -0.894182
3 -0.490303 -0.048233       NaN  1.102955
4 -0.583081  1.471812       NaN  0.940594

In [53]:
# ignore_index=True 를 안줬을 경우
pd.concat([df3, df4])

          a         b         c         d
0 -1.049516 -0.782308  0.068325 -0.663225
1 -1.125727  0.624032 -1.113899  0.774512
2  1.920055 -0.749316 -0.492838 -0.894182
0 -0.490303 -0.048233       NaN  1.102955
1 -0.583081  1.471812       NaN  0.940594